  name: Update GitHub Activity

  on:
    schedule:
      - cron: "0 */6 * * *"
    workflow_dispatch:
  
  permissions:
    contents: write

  jobs:
    update-readme:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Update GitHub Activity
          uses: Readme-Workflows/recent-activity@v2.6.2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            COMMIT_MSG: 'Update GitHub activity'
            MAX_LINES: 5
